project:
  type: website

website:
  title: " "
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    
editor: visual

