project:
  type: website

website:
  title: "Bailey Morrison"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

